#!/usr/bin/env node
// Generates lib/version.ts at build time.
// Version = package.json major.minor.(patch + commits since baseline).
// To reset patch on a minor/major bump: update package.json version and write the
// current HEAD SHA into scripts/version-baseline.txt in the same commit.

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const [major, minor, basePatch] = pkg.version.split('.').map((n) => parseInt(n, 10));

const baselinePath = join(root, 'scripts', 'version-baseline.txt');
const baseline = existsSync(baselinePath)
  ? readFileSync(baselinePath, 'utf8').trim()
  : '';

function git(cmd, fallback = '') {
  try {
    return execSync(cmd, { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

let commitsSinceBaseline = 0;
if (baseline) {
  const count = git(`git rev-list --count ${baseline}..HEAD`, '');
  commitsSinceBaseline = count ? parseInt(count, 10) : 0;
}

const patch = (Number.isFinite(basePatch) ? basePatch : 0) + commitsSinceBaseline;
const version = `${major}.${minor}.${patch}`;
const commitSha = git('git rev-parse --short HEAD', 'unknown');
const buildTime = new Date().toISOString();

const libDir = join(root, 'lib');
if (!existsSync(libDir)) mkdirSync(libDir, { recursive: true });

const out = `// AUTO-GENERATED by scripts/generate-version.mjs. Do not edit.
export const VERSION = ${JSON.stringify(version)};
export const COMMIT_SHA = ${JSON.stringify(commitSha)};
export const BUILD_TIME = ${JSON.stringify(buildTime)};
`;

writeFileSync(join(root, 'lib', 'version.ts'), out);
console.log(`[version] ${version} (${commitSha}) @ ${buildTime}`);
